### ISSUE TITLE
Configurable Resources in Dapr Control Plane Deployment

### ISSUE THREAD

**Issue by ryorke1** [dapr-sandbox/dapr-kubernetes-operator#77]
Is there a way to adjust the manager.yaml deployment for the control plane component such that we can manage the resources? The current configuration is causing us issues and we are currently forcing the resources by quickly modifying the deployment spec after it's deployed. Based on usage, this pod is continually going into OOMKilled state unless we do these changes. IT would be fantastic if we could provide the resource configuration in the COntrol Plane spec. 

Here is where the resources are currently being set:
https://github.com/dapr-sandbox/dapr-kubernetes-operator/blob/4c252bd773f8221365b606c749cdf4704729a742/config/manager/manager.yaml#L98

**Comment by lburgazzoli** [comment]
an option is to tweak the subscription to let OLm alter some parameter of the deployed pods https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/subscription-config.md

**Comment by ryorke1** [comment]
Thanks. I will look into this OLM and see if I can adjust the pod to increase the resources. The only way I can think to replicate it is to deploy a bunch of pods that utilize the operator including adding things like components and HTTPEndpoints. Once the issue occurs, you will notice that the dapr sidecar goes into a crashloop and when you look at the logs you can see that the pod was not able to communicate with the control plane and states that it's shutting down. WHen we looked at the operator, we found it running out of memory causing it to be killed. 

Do you have an example by chance of how to use OLM to modify the control plane pod by chance?

**Comment by lburgazzoli** [comment]
but it looks like what crashes is not the dapr-kubernetes-operator but one of the deployed pods, can you post what actually is crashing ?

**Comment by lburgazzoli** [comment]
Under the hood,  the `dapr-kubernetes-operator` deploys a dapr instance using the regular dapr helm chart so you will end up with the following pods:

```
➜ kubectl get pods
NAME                                     READY   STATUS    RESTARTS      AGE
dapr-operator-699595bbdd-tcmph           1/1     Running   1 (58s ago)   79s
dapr-placement-server-0                  1/1     Running   2 (67s ago)   79s
dapr-sentry-5956f7cd98-z8p58             1/1     Running   0             79s
dapr-sidecar-injector-6fdfb49dfc-xmsfw   1/1     Running   0             79s
```

If the pods that crashes is the `dapr-operator`(or any of those listed above), then you can tweak the related resources using helm values, as described in the dapr helm chart readme: https://github.com/dapr/dapr/blob/master/charts/dapr/README.md#resource-configuration

So if you want to change the dapr-operator memory configuration, then you can apply a resource like:

```yaml
apiVersion: operator.dapr.io/v1alpha1
kind: DaprControlPlane
metadata:
  name: "dapr-control-plane"
  namespace: "dapr-system"
spec:
  # This object provides access to values passed into the Dapr Helm chart
  # https://github.com/dapr/dapr/blob/master/charts/dapr/README.md
  values: 
    dapr_operator:
      resources:
        requests:
          memory: 200Mi
```
